Particular/Workshop

exercises/01 - UI-Composition.md

Removed ``` (backticks) were not not required.

Update 01 - UI-Composition.md

---

exercises/03 - Sagas.md

Corrected first step, specifying actual method name.

Update 03 - Sagas.md

---

exercises/04 - Integration with ITOps.md

Update 04 - Integration with ITOps.md

---

faq.md

Created initial faq that mentions prerequisites checker and an error that popped up this morning.
Anyone in the class can submit PR against this file.

Create initial faq

---

exercises/src/02 Publish-Subscribe/after/externalsystems/MastercardPaymentProvider/Program.cs
exercises/src/02 Publish-Subscribe/before/externalsystems/MastercardPaymentProvider/Program.cs
exercises/src/03 Sagas/after/externalsystems/MastercardPaymentProvider/Program.cs
exercises/src/03 Sagas/before/externalsystems/MastercardPaymentProvider/Program.cs
exercises/src/04 Integration/after/externalsystems/MastercardPaymentProvider/Program.cs
exercises/src/04 Integration/before/externalsystems/MastercardPaymentProvider/Program.cs
exercises/src/99 Final solution/after/externalsystems/MastercardPaymentProvider/Program.cs

And supports testing also via NumPad
@dvdstelt please review and merge.

fixes test url to allow testing even if loopback calls are blocked

---

exercises/03 - Sagas.md

Missing part in exercise 03. ProcessOrder method must be called from Handle methods.

ProcessOrder method must be called from Handle methods

---

exercises/02 - Publish-Subscribe.md

Type of argument changed in description of Exercise 02.3 / 2 (Follow up from discussion during  DDDEurope 2017 workshop)

Fixed type in exercise description

---

demos/CompositeUI-MVC/Divergent.ITOps.ViewModelComposition/CompositionActionFilter.cs
demos/CompositeUI-MVC/Divergent.Sales.ViewModelComposition/OrderDetailsViewModelAppender.cs
demos/CompositeUI-MVC/Divergent.Sales.ViewModelComposition/OrdersListViewModelAppender.cs
demos/CompositeUI-MVC/Divergent.Shipping.ViewModelComposition/OrderDetailsViewModelAppender.cs
demos/CompositeUI-MVC/Divergent.Shipping.ViewModelComposition/OrdersLoadedSubscriber.cs

Remove Task.Run usage in view model appender

---

demos/CompositeUI-MVC/Divergent.ITOps.ViewModelComposition/CompositionActionFilter.cs
demos/CompositeUI-MVC/Divergent.Sales.ViewModelComposition/OrderDetailsViewModelAppender.cs
demos/CompositeUI-MVC/Divergent.Sales.ViewModelComposition/OrdersListViewModelAppender.cs
demos/CompositeUI-MVC/Divergent.Shipping.ViewModelComposition/OrderDetailsViewModelAppender.cs
demos/CompositeUI-MVC/Divergent.Shipping.ViewModelComposition/OrdersLoadedSubscriber.cs

Reverts Particular/Workshop.Microservices#53

Revert "Remove Task.Run usage in view model appender"

---

faq.md

Add a note on localdb standalone installation

---

demos/CompositeUI-MVC/Divergent.ITOps.ViewModelComposition/CompositionActionFilter.cs

Depending on the IoC container of choice interceptors are returned in a non deterministic order. It might happen that appenders are invoked before subscribers have the opportunity to subscribe to events, causing the entire composition process to fail.
@dvdstelt please review.

Ensure subscribers can subscribe before appenders are executed

---

README.md
faq.md

@Particular/microservices-workshop-maintainers please review.

restructure docs and add TOCs

---

README.md

This is based on the branch for #66 so it needs a rebase after #66 is merged. WIP until that time.

ODBC error workaround

---

exercises/01 - UI-Composition.md
exercises/02 - Publish-Subscribe.md
exercises/03 - Sagas.md
exercises/04 - Integration with ITOps.md
exercises/readme.md

@Particular/microservices-workshop-maintainers please review

improve exercise instructions

---

README.md

@Particular/microservices-workshop-maintainers please review

Removes link to the agenda

---

exercises/01 - UI-Composition.md

This just tripped up someone in the workshop.
/cc @Particular/microservices-workshop-maintainers

Added note about client side property casing.

---

exercises/02 - Publish-Subscribe.md
exercises/src/02 Publish-Subscribe/after/Divergent.Shipping/Handlers/PaymentSucceededHandler.cs

Log.Debug message from step 3 doesn't appear in console.
Got this recommendation from one of the attendees in NDC Oslo.

Change Log.Debug to Log.Info

---

exercises/03 - Sagas.md

@Particular/microservices-workshop-maintainers please review/merge. The saga exercises are next up this morning.

improvements to the saga advanced exercises

---

exercises/03 - Sagas.md

@Particular/microservices-workshop-maintainers please review

improve stuff around virtual properties

---

exercises/03 - Sagas.md

/cc @Particular/microservices-workshop-maintainers

add SagaAudit Plugin explanation

---

exercises/03 - Sagas.md
exercises/src/03 Sagas/after/Divergent.Shipping/Sagas/ShippingSaga.cs

clean up some async bits in the saga exercises

---

README.md

@Particular/microservices-workshop-maintainers please review/merge.

add VS 2017 to prerequisites

---

README.md

specify a Windows client edition

---

exercises/License.xml

Updated the license file with a new one valid till end of October 2017

New license

---

exercises/02-publish-subscribe/instructions.md

* It takes quite some time to hit `F5` and see if it runs. Feels like big-bang approach. Should we make the whole process more incremental? e.g. put explicit CTA to run current version of the the exercise?
* How much commentary do we expect from the Trainer? e.g. 
* Inside `OrderSubmittedHandler` in `Finance` it might not be obvious why we need the `InitiatePaymentProcessCommand`
* Should we go through `PaymentClient` to show what kind of data it requires to make a payment before we show `InitiatePaymentProcessCommand` creation?
* Should we mention potential ordering issues in `Shipping`?
* Do we go through error cases or wait until `Exercise 3`?

Exercise 2 review for TWF

---

README.md
exercises/02-publish-subscribe/instructions.md
exercises/03-sagas/instructions.md
exercises/04-integration/instructions.md

Fixes #89 
This is an alternate way of adding advanced exercises from https://github.com/Particular/Workshop.Microservices/pull/109
Instead of having module 05 (without any code) the exercise was split into advanced exercises for module 02 and 04.

Add ServiceInsight and ServicePulse v2

---

demos/asp-net-core/Divergent.Website/Views/Orders/Index.cshtml

Connects to https://github.com/Particular/Workshop.Microservices/issues/137
Fix https://github.com/Particular/Workshop.Microservices/issues/137

Use html tag helpers

---

demos/asp-net-core/Divergent.Sales.API.Host/Divergent.Sales.API.Host.csproj
demos/asp-net-core/Divergent.Shipping.API.Host/Divergent.Shipping.API.Host.csproj

Connects to https://github.com/Particular/Workshop.Microservices/issues/136
Fix https://github.com/Particular/Workshop.Microservices/issues/136

Align default namespace and assembly name with project name

---

demos/asp-net-core/Divergent.Sales.API.Host/App.config
demos/asp-net-core/Divergent.Shipping.API.Host/App.config

Smoke tested and it seems to work just fine.

user local folder for demo persistence

---

demos/asp-net-core/Divergent.Sales.ViewModelComposition/OrderDetailsViewModelAppender.cs
demos/asp-net-core/Divergent.Sales.ViewModelComposition/OrdersListViewModelAppender.cs
demos/asp-net-core/Divergent.Shipping.ViewModelComposition/OrderDetailsViewModelAppender.cs
demos/asp-net-core/Divergent.Shipping.ViewModelComposition/OrdersLoadedSubscriber.cs

As @janovesk suggested. Please review.

Remove all ConfigureAwait from end user code

---

README.md

See https://github.com/Particular/Workshop.Microservices/issues/151

clarified that SQL Express can be used

---

demos/asp-net-core/Divergent.Shipping.Data/Models/Shipment.cs

To match [`Order.cs`](https://github.com/Particular/Workshop.Microservices/blob/a96bd7faac7955f26586553a611b9e1cb92be1bc/demos/asp-net-core/Divergent.Sales.Data/Models/Order.cs) (I missed this in https://github.com/Particular/Workshop.Microservices/pull/161).

shipment tweaks

---

demos/asp-net-core/ITOps.ViewModelComposition.Mvc/CompositionFilter.cs
demos/asp-net-core/ITOps.ViewModelComposition.Mvc/MvcBuilderExtensions.cs

Fix https://github.com/Particular/Workshop.Microservices/issues/146

Rename MVC filter from CompositionActionFilter to CompositionFilter

---

README.md

Add .NET 4.6.1 to prerequisites

---

exercises/01-composite-ui/README.md
exercises/02-publish-subscribe/README.md
exercises/03-sagas/README.md
exercises/04-integration/README.md

In two documents there was a link to Google Groups. Changed it to new Discourse platform.
One of those two documents contained a link at the bottom of the exercise, I added a conclusion with link to the bottom of all exercises to be consistent. It's a good thing to have the ability for attendees (or anyone just looking at this repo) to discuss the exercises and workshop content after the workshop.

Add exercise conclusions.

---

README.md

At first glance, it looks like "Install the pre-requisites" is the only part that you need to do. This makes it clear that there are several larger steps in the preparation process.

Add TOC to "preparing your machine"

---

README.md

The demos section is of secondary importance to attendees. We will show the demos during the workshop. The most important sections for the attendees before/during attendance are the setup and running of the exercises.

Move demos further down in readme

---

demos/asp-net-core/ITOps.ViewModelComposition.Gateway/ApplicationBuilderExtensions.cs
demos/asp-net-core/ITOps.ViewModelComposition/CompositionHandler.cs

Some small changes I made before showing the demo in the last workshop.

Minor refactoring

---

README.md

Running the powershell script to create LocalDB instance I got a strange error due to the script starting with an `@`. Removing the `@` all worked fine.

Strange error if the script starts with an @

---

exercises/02-publish-subscribe/README.md

Fix link to instructions for preparing your machine for the advanced exercise

Fix link to instructions for preparing your machine for the advanced exercise

---

exercises/01-composite-ui/README.md
exercises/03-sagas/README.md
exercises/04-integration/README.md

Fix some links

---

exercises/03-sagas/README.md
exercises/03-sagas/after/Divergent.Shipping/Sagas/ShippingSaga.cs
exercises/04-integration/after/Divergent.Shipping/Sagas/ShippingSaga.cs
exercises/04-integration/before/Divergent.Shipping/Sagas/ShippingSaga.cs

As pointed out by @bryanjhogan during our workshop at NDC London.

remove redundant setting of saga data OrderId

---

exercises/02-publish-subscribe/README.md
exercises/03-sagas/README.md
exercises/04-integration/README.md

To match how they are shown in the VS solution properties window.

sort start up projects in exercise instructions

---

build.cmd

I've encountered the same problem as described here: https://github.com/Particular/Workshop/issues/227
Here's the fix. 
Fixes #227

Fix build.cmd to handle spaces in user folder path

---

README.md
exercises/scripts/Setup-Databases.sql
exercises/scripts/Setup-LocalDBInstance.ps1
exercises/scripts/Teardown-LocalDBInstance.ps1

- Switches to promote script to local db with SQLCMD
- Adds explanation if necessary to setup local db

Enable DB scripts working with SQL Local DB 2017 and simplify DB setup

---

README.md

add ODBC driver to machine prep

---

exercises/02-publish-subscribe/after/Divergent.Sales.API/NServiceBusConfig.cs
exercises/02-publish-subscribe/before/Divergent.Sales.API/NServiceBusConfig.cs
exercises/03-sagas/after/Divergent.Sales.API/NServiceBusConfig.cs
exercises/03-sagas/before/Divergent.Sales.API/NServiceBusConfig.cs
exercises/04-integration/after/Divergent.Sales.API/NServiceBusConfig.cs
exercises/04-integration/before/Divergent.Sales.API/NServiceBusConfig.cs
exercises/shared-api-gateway/ITOps.EndpointConfig/EndpointConfigurationExtensions.cs

Relates to https://github.com/Particular/DeveloperEducation/issues/1437

Fix license path

---

exercises/02-publish-subscribe/after/Divergent.Finance/Divergent.Finance.csproj
exercises/02-publish-subscribe/after/Divergent.Sales.API/Divergent.Sales.API.csproj
exercises/02-publish-subscribe/after/Divergent.Sales/Divergent.Sales.csproj
exercises/02-publish-subscribe/after/Divergent.Shipping/Divergent.Shipping.csproj
exercises/04-integration/before/Divergent.Sales.API/NServiceBusConfig.cs

This PR fixes inconsistencies introduced by https://github.com/Particular/Workshop/pull/274

align before-after solutions

---

.gitignore

Added small change to ignore vs2017 userfiles

Gitignore userfiles

---

exercises/scripts/Setup-LocalDBInstance.ps1

allow database set up script to run regardless of current directory

---

README.md

Installing SP for the first time using the platform installer will result in 2 warnings. Updating the readme so that the users are aware and can safely ignore those warnings are proceed with the installation.

update the readme to help with SP installation using the platform installer

---

README.md

Copy edit for https://github.com/Particular/Workshop/pull/292/files

copy edit for platform installation changes

---

exercises/02-publish-subscribe/README.md

Exercise 2's Advanced exercise was slightly misleading with respect to the heartbeats. Fixed that. 
Also added incorporating metrics for monitoring.

Made the instructions for Exercise2 better

---

targets/Program.cs

I think this was a copypasta artifact.

remove inappropriate copyright

---

exercises/03-sagas/README.md

Workshop attendee found an error

Fix async error

---

exercises/License.xml

Build Stuff: 17th - 18th Nov
.NETworking: 29th - 30th Nov
https://particular.net/events

new license to cover the Build Stuff and .NETworking workshops

---

targets/Program.cs
targets/Targets.csproj

switch to SimpleExec

---

README.md

@ramonsmits I thought that some of the changes from https://github.com/Particular/Workshop/pull/316 were valuable, so I've re-created them here (with some tweaks).

prep improvements

---

README.md

- Fixes the MS SQL Server 2017 download link

Fixes the MS SQL Server 2017 download link

---

README.md

Applies markdown linting rules to the readme file

Lint README markdown
